name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scikit-learn flask flask-sqlalchemy spacy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m spacy download en_core_web_sm
      - name: Run tests
        run: |
          pytest -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn flask flask-sqlalchemy spacy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m spacy download en_core_web_sm
      
      - name: Configure GitLab Integration
        run: |
          echo "Setting up GitLab integration"
          # The GitLab token is stored in GitHub Secrets
          echo "GITLAB_TOKEN=${{ secrets.Gitlab }}" >> $GITHUB_ENV
      
      - name: Update GitLab CI configurations
        run: |
          python gitlab_api.py update_ci_config
        env:
          GITLAB_TOKEN: ${{ secrets.Gitlab }}
      
      - name: Build AI Model
        run: |
          python ai_model.py train
      
      - name: Package Application
        uses: actions/upload-artifact@v3
        with:
          name: devops-ai-app
          path: |
            app.py
            models.py
            routes.py
            ai_model.py
            gitlab_api.py
            static/
            templates/
            main.py
